=== David-Rodriguez-cabrera/xmlRepo/clientes/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT Sede-central (Sede)*>

<!ELEMENT Sede (cliente)*>
<!ATTLIST Sede
    codigo CDATA #IMPLIED
  >

<!ELEMENT cliente (codigocliente|nViviendas|coste|Resumen|plazo)*>

<!ELEMENT codigocliente (#PCDATA)>

<!ELEMENT nViviendas (#PCDATA)>

<!ELEMENT coste (#PCDATA)>

<!ELEMENT Resumen (#PCDATA)>

<!ELEMENT plazo (#PCDATA)>

=== David-Rodriguez-cabrera/xmlRepo/clientes/clientes-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sede-central SYSTEM "clientes.dtd">

<Sede-central>
    <Sede codigo="A1234567">
        <empleado>Paco</empleado>
        <fecha>2/2/2002</fecha>
        <descripcion>Descripcion</descripcion>
        <cliente>
            <codigocliente>SAA-001</codigocliente>
            <nViviendas>2</nViviendas>
            <coste>100.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 1 mes </plazo>
        </cliente>
        <cliente>
            <codigocliente>SAA-001</codigocliente>
            <nViviendas>1</nViviendas>
            <coste>110.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 2 semanas </plazo>
        </cliente>
    </Sede> 
    <Sede codigo="B1234567">
        <empleado>Paco</empleado>
        <fecha>2/2/2002</fecha>
        <descripcion>Descripcion</descripcion>
        <cliente>
            <codigocliente>SBB-001</codigocliente>
            <nViviendas>2</nViviendas>
            <coste>100.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 1 mes </plazo>
        </cliente>
        <cliente>
            <codigocliente>SBB-002</codigocliente>
            <nViviendas>1</nViviendas>
            <coste>110.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 2 semanas </plazo>
        </cliente>
    </Sede> 
    <Sede codigo="C1234567">
        <empleado>Paco</empleado>
        <fecha>2/2/2002</fecha>
        <descripcion>Descripcion</descripcion>
        <cliente>
            <codigocliente>SCC-001</codigocliente>
            <nViviendas>2</nViviendas>
            <coste>100.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 1 mes </plazo>
        </cliente>
        <cliente>
            <codigocliente>SCC-002</codigocliente>
            <nViviendas>1</nViviendas>
            <coste>110.000</coste>
            <Resumen> La primera vivienda cuenta con...</Resumen>
            <plazo> 2 semanas </plazo>
        </cliente>
    </Sede>
</Sede-central>
