=== David-Rodriguez-cabrera/xmlRepo/concesionario/concesionario.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/actividad-ej-3.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Almacen-Concesionario SYSTEM "actividad-ej-3.dtd">

    <Almacen-Concesionario>
    ...
    </Almacen-Concesionario>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Almacen-Concesionario (coche)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT coche (codigo-coche|marca|modelo|matricula|caballos|plazas|nPuertas)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigo-coche (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT marca (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT modelo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT matricula (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT caballos (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plazas (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nPuertas (#PCDATA)>

=== David-Rodriguez-cabrera/xmlRepo/concesionario/concesionario-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Almacen-Concesionario SYSTEM "concesionario.dtd">

<Almacen-Concesionario>
    <coche>
        <codigo-coche> 1 </codigo-coche>
        <marca> Seat </marca>
        <modelo> Ibiza Quinta generacion 2018 </modelo>
        <matricula> 1534 JXK </matricula>
        <caballos> 95 </caballos>
        <plazas> 5 </plazas>
        <nPuertas> 4 </nPuertas>
        </coche>
    <coche>
        <codigo-coche> 2 </codigo-coche>
        <marca> Seat </marca>
        <modelo> Ibiza Cuarta generacion 2017 </modelo>
        <matricula> 1588 JXK </matricula>
        <caballos> 80 </caballos>
        <plazas> 5 </plazas>
        <nPuertas> 4 </nPuertas>
        </coche>
    <coche>
        <codigo-coche> 3 </codigo-coche>
        <marca> Seat </marca>
        <modelo> Ibiza Sexta generacion 2018 </modelo>
        <matricula> 1600 JXK </matricula>
        <caballos> 110 </caballos>
        <plazas> 5 </plazas>
        <nPuertas> 4 </nPuertas>
        </coche>
</Almacen-Concesionario>
